Fix random failure in test_querystring.robot
plone/Products.CMFPlone pull request #3362
Opened 2021-11-19 18:32 UTC by wesleybl

Wait for the input to be visible, before trying to put a value on it.

This fixes the error:

```
Element with locator 'jquery=.select2-drop-active[style*="display: block;"] input' not found.
```

See: https://jenkins.plone.org/job/pull-request-6.0-3.9/555

2021-11-19 18:32 UTC, mister-roboto commented
@wesleybl thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-11-19 18:32 UTC, wesleybl commented
@jenkins-plone-org please run jobs

2021-11-19 19:05 UTC, wesleybl commented
@jenkins-plone-org please run jobs

2021-11-19 23:37 UTC, ale-rt approved these changes

2021-11-20 07:14 UTC, jensens requested changes
Please add a news entry for change-log

2021-11-20 08:51 UTC, ale-rt commented
> Please add a news entry for change-log

Do you think it is required for such a small test related change? 
I would be fine merging it anyway.
Although I have no power to do so if all the checks are not green.

2021-11-20 09:57 UTC, mauritsvanrees commented
Agreed. I merge.

2021-11-20 09:57 UTC, merged

2021-11-20 09:59 UTC, mauritsvanrees commented
@ale-rt You should have had that right long ago. :-) I have now given you the Owner role on the plone organisation.

2021-11-20 14:53 UTC, wesleybl commented
> @ale-rt You should have had that right long ago. :-) I have now given you the Owner role on the plone organisation.

@ale-rt  You can test your new powers here: #3361