Cleanup Portal
plone/Products.CMFPlone pull request #3366
Opened 2021-11-24 21:17 UTC by jensens

Minor cleanups and removal of dead code.

2021-11-24 21:17 UTC, mister-roboto commented
@jensens thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-11-24 23:21 UTC, ale-rt commented on Products/CMFPlone/Portal.py
> -    def availableLanguages(self):
This will fix #3237

2021-11-24 23:21 UTC, ale-rt commented
@jenkins-plone-org please run jobs

2021-11-24 23:24 UTC, ale-rt requested changes
I see this is still a draft.
Maybe you plan to add more to it.
Anyway if the tests are green I would merge it.
A towncrier entry 3237.bugfix would be appreciated :)

2021-11-24 23:28 UTC, jensens commented on Products/CMFPlone/Portal.py
> -    def availableLanguages(self):
indeed :-)

2021-11-24 23:32 UTC, jensens commented
yes, I create them mostly as draft and make them ready if all set. Now ready!

2021-11-24 23:32 UTC, jensens commented
@jenkins-plone-org please run jobs

2021-11-24 23:34 UTC, jensens commented
@jenkins-plone-org please run jobs

2021-11-25 07:45 UTC, ale-rt approved these changes

2021-11-25 11:33 UTC, merged