Jmevissen 3241 move prefs error log from skins to browser view
plone/Products.CMFPlone pull request #3372
Opened 2021-12-02 10:48 UTC by jmevissen

2021-12-02 10:48 UTC, mister-roboto commented
@jmevissen thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-12-02 12:56 UTC, mauritsvanrees requested changes
Thank you!

A couple of things:

- Please merge master in here, or rebase this branch on top of master. Master got the new `autoinclude` stuff merged today, which makes it harder to try out your branch: I get an error when I use the current coredev buildout and switch to your branch.
- I added two minor inline comments, about class/template.
- You requested a review from @agitator and it could indeed use some love/hints by him. Some more margin/padding in the logentry table would be good, and the textarea for the ignored exception types probably looks better on a new line, as it was previously. See screenshot.
- Strangely, on current master, so still with this control panel in the skins, I get an 'insufficient privileges' error because I cannot access `icons.tag`. I have not seen that yet. Maybe I did something weird. Anyway, I don't have this problem on your branch, so that is a good improvement. Does anyone else have this same problem on master? Then it would be good to merge this soon, even without the requested changes addressed.

![Screenshot 2021-12-02 at 13 50 41](https://user-images.githubusercontent.com/210587/144425566-4d403157-b189-46bc-81fd-ee95143779e9.png)

2021-12-02 12:56 UTC, mauritsvanrees commented on Products/CMFPlone/controlpanel/browser/configure.zcml
> +      class=".prefs_error_log_form.PrefsErrorLogForm"
Since the class does not really have any code, you can remove it here, and use `template="prefs_error_log_form.pt"`.

2021-12-02 12:56 UTC, mauritsvanrees commented on Products/CMFPlone/controlpanel/browser/configure.zcml
> +      permission="cmf.ManagePortal"
Same here: replace `class` with the proper `template`.

2021-12-03 15:48 UTC, agitator commented
@jmevissen ping me on discord when ready ;-)

2021-12-03 17:42 UTC, mauritsvanrees commented
I want to include this in the alpha 2, which may be really soon if I have enough time. I nothing changes before that, I will happily merge this and it can be improved in the third alpha.

2021-12-03 17:43 UTC, mauritsvanrees commented
@jenkins-plone-org please run jobs

2021-12-03 22:05 UTC, jensens approved these changes
One less i skins, I approve 

@mauritsvanrees comments are valid, would be good to have a cleanup PR afterwards, but thats not a show stopper

2021-12-03 22:07 UTC, merged

2021-12-09 09:18 UTC, laulaz commented
> * Strangely, on current master, so still with this control panel in the skins, I get an 'insufficient privileges' error because I cannot access `icons.tag`. I have not seen that yet. Maybe I did something weird. Anyway, I don't have this problem on your branch, so that is a good improvement. Does anyone else have this same problem on master? Then it would be good to merge this soon, even without the requested changes addressed.

@mauritsvanrees see issue here #3335, you did nothing wrong 😉