Admin UI tweaks
plone/Products.CMFPlone pull request #3640
Opened 2022-09-13 08:30 UTC by jensens

- white textcolor on button
- place link to site

2022-09-13 08:30 UTC, mister-roboto commented
@jensens thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-09-13 08:32 UTC, jensens commented
@jenkins-plone-org please run jobs

2022-09-13 12:16 UTC, stevepiercy commented
I don't suppose you have any before and after screenshots?

2022-09-13 12:40 UTC, jensens commented
No screenshots, sorry.
a) The link on the button was was in dirty yellow and now its white.
b) I placed a link to the site after migration is done. There was not any link available and one had to edit the address bar to get anywhere.

2022-09-13 12:45 UTC, stevepiercy commented
I'd like to offer constructive feedback, but I have not looked into building, previewing, and testing this repo. I trust that you know what you're doing, and the changes look fine to me.

2022-09-13 15:03 UTC, mauritsvanrees commented
In the Zope root, before:

![Screenshot 2022-09-13 at 17 01 24](https://user-images.githubusercontent.com/210587/189936594-1f202f8d-2ebe-4134-a111-f337251e2bd4.png)

and after:

![Screenshot 2022-09-13 at 17 01 50](https://user-images.githubusercontent.com/210587/189936708-460829f6-53ff-4997-b50d-1b2781c27743.png)

Much better.

And for the other part: I have been missing that link! Thanks for putting it back. I would do it in a different part of the template though. See inline comments.

2022-09-13 15:03 UTC, mauritsvanrees requested changes

2022-09-13 15:41 UTC, jensens commented on Products/CMFPlone/browser/templates/plone-upgrade.pt
> +            <h2>${context/Title} <small>(id=${context/getId})</small></h2>
I thought about that, but having a h2 a link feels odd somehow.

2022-09-13 15:41 UTC, jensens commented on Products/CMFPlone/browser/templates/plone-upgrade.pt
> +              <span i18n:translate="" tal:omit-tag="">Your <a href="${context/absolute_url}">site</a> is up to date.</span>
ok, this is a reason for my lazy me to ignore its a h2....

2022-09-13 15:53 UTC, jensens commented
I really do not like having a fat link on a h2. so, my idea is to place the id as the path (which is IMO the more valuable information) linked to the site below the title.

2022-09-13 16:00 UTC, jensens commented
@stevepiercy sorry, next time I will provide screenshots. It's just - my i3wm based setup lost the capability to take screenshots. Now I am able again to provide those.

2022-09-13 21:36 UTC, stevepiercy commented
The last screenshot looks good to me!

2022-09-15 08:07 UTC, mauritsvanrees approved these changes

2022-09-15 08:07 UTC, merged