Don't set "path" for Plone site root
plone/Products.CMFPlone pull request #3755
Opened 2023-03-29 07:31 UTC by malthe

It doesn't make sense to add a path query targeting the site root – that's a "noop", only making things slower.

This is backported from #3753.

2023-03-29 07:31 UTC, mister-roboto commented
@malthe thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-03-29 07:36 UTC, ale-rt approved these changes

2023-03-29 07:38 UTC, malthe commented
@jenkins-plone-org please run jobs

2023-03-30 13:54 UTC, petschki requested changes

2023-03-30 13:54 UTC, petschki commented on Products/CMFPlone/browser/search.py
> +from plone.base.interfaces.siteroot import IPloneSiteRoot
```suggestion
from Products.CMFPlone.interfaces import IPloneSiteRoot
```

in Plone 5.2 there is no `plone.base`

2023-03-30 22:01 UTC, gforcada approved these changes

2023-04-15 15:18 UTC, petschki approved these changes

2023-04-15 15:20 UTC, petschki commented
@jenkins-plone-org please run jobs

2023-04-17 10:46 UTC, merged