fixes #3962
plone/Products.CMFPlone pull request #3963
Opened 2024-05-20 20:24 UTC by jensens

#3962 CMFPlone must not depend on plone.api

2024-05-20 20:24 UTC, mister-roboto commented
@jensens thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-05-20 20:25 UTC, jensens commented
@jenkins-plone-org please run jobs

2024-05-20 20:25 UTC, jensens commented
@gforcada can we have these plone/meta tests for circular dependencies on CMFPlone too?

2024-05-23 01:03 UTC, davisagli requested changes

2024-05-23 01:03 UTC, davisagli commented on Products/CMFPlone/controlpanel/browser/error_log_form.py
> +        portal_membership = getToolByName("portal_membership")
@jensens Doesn't getToolByName need a context?

2024-05-23 08:26 UTC, jensens commented on Products/CMFPlone/controlpanel/browser/error_log_form.py
> +        portal_membership = getToolByName("portal_membership")
```suggestion
        portal_membership = getToolByName(self.context, "portal_membership")
```

2024-05-23 08:27 UTC, jensens commented on Products/CMFPlone/controlpanel/browser/error_log_form.py
> +        portal_membership = getToolByName("portal_membership")
Indeed.

2024-05-23 09:50 UTC, merged