Use details element for collapsibles in the resource registry
plone/Products.CMFPlone pull request #3976
Opened 2024-06-15 11:01 UTC by reinhardt

Makes it possible to toggle elements even with broken or missing javascript.

However, this changes the look & feel. The CSS is not applied any more because some classes were removed so that the accordion JS does not interfere. Maybe there's a better way to do this, or maybe we just need some additional CSS?

![2024-06-15-12-58-42_2552x1368](https://github.com/plone/Products.CMFPlone/assets/202439/3a6bfc3b-4682-4a15-8bf8-a2afdac7ac9c)

Fixes #3942

2024-06-15 11:01 UTC, mister-roboto commented
@reinhardt thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-06-15 11:06 UTC, rohnsha0 commented
@jenkins-plone-org please run jobs

2024-06-15 23:46 UTC, mauritsvanrees commented
+1 from me.  A few tests are failing though.

2024-06-16 12:09 UTC, thet commented
I've added some classes and styles. It now looks almost like before:

![image](https://github.com/plone/Products.CMFPlone/assets/170891/9c832c87-eb77-4a10-b796-566bfc242769)

PR: https://github.com/plone/plonetheme.barceloneta/pull/374

2024-06-17 10:41 UTC, thet commented
Now with label wrapping their inputs and no id's being duplicated (tnx @ale-rt  for pointing this out).

Together with the changes in plonetheme.barceloneta, this looks like that:

![image](https://github.com/plone/Products.CMFPlone/assets/170891/d6eddfa6-596f-4db1-a986-1d654f80cffc)

2024-06-17 15:38 UTC, reinhardt commented
Awesome, thanks @thet! LGTM (Though I can't give an approving review because I created the PR :stuck_out_tongue:)

2024-06-18 06:04 UTC, petschki requested changes
Input fields aren't 100% width because of nested label/input markup. BS 5 default isn't nested ... see screenshot: first without nesting, second input inside label.

<img width="1302" alt="Bildschirmfoto 2024-06-18 um 08 03 33" src="https://github.com/plone/Products.CMFPlone/assets/511761/9b541621-b0e4-4042-9bf5-ba89e08ccff5">

2024-06-18 10:44 UTC, thet commented
@petschki did you also check out the plonetheme.barceloneta branch from https://github.com/plone/plonetheme.barceloneta/pull/374 ?

For me, it looks like this:

![image](https://github.com/plone/Products.CMFPlone/assets/170891/6ff6a9af-1dbe-4bb6-a5ec-95eeb679a211)

2024-06-18 16:22 UTC, MrTango requested changes
looks good, but i would keep the h2 instead of the strong tags, as it is semantically better.

2024-06-18 17:10 UTC, thet commented
@jenkins-plone-org please run jobs

2024-06-19 08:01 UTC, MrTango approved these changes

2024-06-19 08:57 UTC, petschki approved these changes
@thet sorry ... my already checked out barceloneta was on the wrong branch ... looks good now here.

2024-06-19 10:49 UTC, merged