Refactor site creation
plone/Products.CMFPlone pull request #3981
Opened 2024-06-19 20:09 UTC by mauritsvanrees

This is part of https://github.com/plone/Products.CMFPlone/issues/3961

This affects the site creation process when `plone.distribution` is not available.  See the individual commits for details.  In this case, the plone-overview page on the Zope root looks like this:

<img width="776" alt="Screenshot 2024-06-19 at 20 38 50" src="https://github.com/plone/Products.CMFPlone/assets/210587/4ff888de-f177-43c2-a6f2-df9ca6cb4dff">

The Advanced version of the Add Plone Site form is gone.  For advanced options you should use a Plone Distribution.

This needs a change in `plone.app.testing`, otherwise loads of tests fail.  Only a one line change though.  I will link the PR.

I will keep this as Draft PR for now.

2024-06-19 20:09 UTC, mister-roboto commented
@mauritsvanrees thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-06-20 09:49 UTC, stevepiercy requested changes
Polish up the messages.

2024-06-20 09:49 UTC, stevepiercy commented on Products/CMFPlone/browser/templates/plone-overview.pt
> +                If you see this text, that means you do not have this package yet.
Suggest the following wording.

```
Starting with Plone 6.1, default content is not loaded into the site.
If you want to load the default content, you should install the <code>plone.classicui</code> package.
If you see this text, that means you have not installed that package yet.
```

2024-06-20 09:49 UTC, stevepiercy commented on news/3961.breaking.3
> +We never setup content anymore.  Use a Plone Distribution if you need this.
```suggestion
We no longer load default content. Use a Plone Distribution if you need this.
```

2024-06-27 17:33 UTC, mauritsvanrees commented on Products/CMFPlone/browser/templates/plone-overview.pt
> +                If you see this text, that means you do not have this package yet.
Suggestion applied, thanks.

2024-06-27 22:00 UTC, stevepiercy approved these changes
Thank you! Looks good so far.

2024-09-28 18:04 UTC, stevepiercy commented
Upon merge and release, we need to update the documentation. See https://github.com/plone/documentation/issues/1721

2024-10-08 09:11 UTC, merged