Changed twitter link to x
plone/Products.CMFPlone pull request #3995
Opened 2024-08-05 14:31 UTC by SarthakPaandey

As part of the recent rebranding of Twitter to X, we propose updating all references to Twitter links (twitter.com) in the codebase and documentation to x.com. This change aligns with the platform's new branding and ensures consistency in all related references.
This update is necessary to maintain brand consistency within the project and provide an accurate reflection of the external service's current branding. By updating the links to x.com, we ensure that users and developers are not confused by outdated references to Twitter.
Fixes issue #3994

2024-08-05 14:31 UTC, mister-roboto commented
@SarthakPaandey thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-08-05 14:32 UTC, SarthakPaandey commented
@jenkins-plone-org please run jobs

2024-08-05 15:03 UTC, SarthakPaandey commented
I have signed it.

2024-08-05 15:04 UTC, SarthakPaandey commented
@gforcada kindly look into this pull request.

2024-08-05 16:21 UTC, rohnsha0 commented
I'm not sure we need this PR. As far as I know, any attempt to access twitter.com gets redirected to x.com. That means all the links that are currently pointing to twitter.com aren't broken.

Am I missing something? @SarthakPaandey 
&nbsp;

> @gforcada kindly look into this pull request.

please dont tag like this. request a review instead

2024-08-05 16:25 UTC, rohnsha0 reviewed
I'm not sure we need this PR. As far as I know, any attempt to access twitter.com gets redirected to x.com. That means all the links that are currently pointing to twitter.com aren't broken.

Am I missing something? @SarthakPaandey 
Infact, changing the user-side mentions of `Twitter` to `X` makes more sense
&nbsp;

> @gforcada kindly look into this pull request.

please dont tag like this. request a review instead

2024-08-05 17:13 UTC, SarthakPaandey commented
I know but for future reference it is kind of good and also I want to contribute something to the Plone community.

2024-08-05 17:16 UTC, SarthakPaandey commented
Yes @rohnsha0.

2024-08-06 06:27 UTC, rohnsha0 commented
Okay, but please change the references in https://github.com/plone/plone.base/blob/3a5aef0e158da872d2280cb0150d94c65417120f/src/plone/base/interfaces/controlpanel.py#L1593-L1602 as well. Submit a separate PR for those changes, and include a reference to this PR.

2024-08-06 06:58 UTC, rohnsha0 requested changes
Ill suggest changing to

```
project_urls={
        # other entries...
        "X (formerly Twitter)": "https://x.com/plone",
        # other entries...
    },
```

2024-08-06 09:18 UTC, SarthakPaandey commented
> Ill suggest changing to
> 
> ```
> project_urls={
>         # other entries...
>         "X (formerly Twitter)": "https://twitter.com/plone",
>         # other entries...
>     },
> ```

should i add x.com or not?

2024-08-06 09:48 UTC, rohnsha0 commented
> > Ill suggest changing to
> > ```
> > project_urls={
> >         # other entries...
> >         "X (formerly Twitter)": "https://twitter.com/plone",
> >         # other entries...
> >     },
> > ```
> 
> should i add x.com or not?

Ofc

2024-08-06 10:03 UTC, stevepiercy commented
@SarthakPaandey you should first satisfy contributing requirements, as I [mentioned in the original issue](https://github.com/plone/Products.CMFPlone/issues/3994#issuecomment-2269758616). We cannot accept a PR until you do so. Thank you!

2024-08-06 11:33 UTC, SarthakPaandey commented
I have already signed the agreement. Do i need to submit it anywhere?

2024-08-06 19:00 UTC, stevepiercy commented
> I have already signed the agreement. Do i need to submit it anywhere?

Yes. Again, please read my original comment about contributing. Thank you!

2024-08-14 09:02 UTC, mauritsvanrees commented
I as Plone Release Manager am happy to accept this small change, even if the contributor agreement has not been handled yet.  I can make such exceptions.
First changing the title to "X (formerly Twitter)" as suggested may be good.

2024-10-23 10:10 UTC, petschki commented
I'd remove it completely and additionally delete the plone account on X ... we really should not support this platform.

2024-10-23 10:45 UTC, rohnsha0 commented
> I'd remove it completely and additionally delete the plone account on X ... we really should not support this platform.

As of today, Plone is available on X... Right?!

2024-10-23 23:52 UTC, stevepiercy requested changes

2024-10-23 23:52 UTC, stevepiercy commented on setup.py
> +        "Twitter": "https://x.com/plone",
```suggestion
        "X (formerly Twitter)": "https://x.com/plone",
```

2024-10-23 23:52 UTC, mister-roboto commented
@SarthakPaandey you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-10-23 23:52 UTC, stevepiercy commented
> I'd remove it completely and additionally delete the plone account on X ... we really should not support this platform.

I wholeheartedly agree. That discussion, however, needs to take place amongst the @plone/marketing-communications Team, and is outside the scope of this PR.

Meanwhile each of us can unfollow Plone on Xwitter, and follow on [Mastodon](https://plone.social/@plone), bidding them a fond "Hello there!".

@mauritsvanrees can we just merge this PR for now?

2024-10-24 02:05 UTC, mister-roboto commented
@SarthakPaandey you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-10-24 02:56 UTC, SarthakPaandey commented
![image](https://github.com/user-attachments/assets/b982ed88-2838-43a6-a3eb-92382f38a3aa)
I have signed it already.

> @SarthakPaandey you need to sign the Plone Contributor Agreement to merge this pull request.
> 
> Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-10-24 07:38 UTC, stevepiercy commented
@SarthakPaandey would you please follow up per https://plone.org/foundation/contributors-agreement:

> ## I signed the Agreement, but haven't been given access yet?
>
> Please allow a week for a response. Volunteers process the Contributor Agreements. If you have issues, such as making a spelling error in your email or GitHub username, please contact agreements@plone.org.

2024-10-24 11:15 UTC, mauritsvanrees approved these changes
This change is fine even if something is wrong with regards to the contributor agreement.  I merge.

Thanks!

2024-10-24 11:16 UTC, merged