Allow bundles to be rendered after "theme" and "custom" bundles.
plone/Products.CMFPlone pull request #4054
Opened 2024-11-08 18:49 UTC by thet

Bundles can now depend on the automatically added "theme" and "custom" bundles from plone.app.theming and be rendered after those (e.g. after the plonetheme.barceloneta CSS).

This allows to override a theme with custom CSS from a bundle instead of having to add the CSS customizations to the registry via the "custom_css" settings. As a consequence, theme customization can now be done in the filesystem in ordinary CSS files instead of being bound to a time consuming workflow which involces upgrading the registry after every change.

2024-11-08 18:50 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-11-08 18:52 UTC, thet commented on Products/CMFPlone/resources/browser/resource.py
> +        css_names += ["theme", "custom"]
See below in https://github.com/plone/Products.CMFPlone/pull/4054/files#diff-9e095767a08db89a248c84c46d31c75898eed2d7dc40b0757a835bb2af0ed95bR143 and https://github.com/plone/Products.CMFPlone/pull/4054/files#diff-9e095767a08db89a248c84c46d31c75898eed2d7dc40b0757a835bb2af0ed95bR165

If "theme" or "custom" does not exist (both added in line 192+) the bundle dependency cannot be resolved and the bundle is not included in the rendered output.

2024-11-08 18:52 UTC, thet commented
@jenkins-plone-org please run jobs

2024-11-08 20:47 UTC, stevepiercy commented
This needs to be documented, but I'm not sure where. Perhaps in [Theming of Classic UI](https://6.docs.plone.org/classic-ui/theming/index.html)? That section is so sad.

2024-11-09 11:52 UTC, jensens approved these changes
I think this is a good enhancement. Anyway, this needs some documentation, since it is not obvious.

2024-11-09 11:53 UTC, jensens commented
> This needs to be documented, but I'm not sure where. Perhaps in [Theming of Classic UI](https://6.docs.plone.org/classic-ui/theming/index.html)? That section is so sad.

I think this should go into https://6.docs.plone.org/classic-ui/static-resources.html

2024-11-11 08:36 UTC, petschki requested changes
Somehow I could not get this to work correctly. I checked out your branch and tested in with the `plone-fullscreen` bundle:

1. I added `custom` to depends, but the CSS was not added... also the `.js` is missing (because custom is only for CSS defined, but the bundle has JS also)
2. I added `theme` to depends and get the following traceback:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module zope.browserpage.simpleviewclass, line 44, in __call__
  Module Products.Five.browser.pagetemplatefile, line 127, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 134, in pt_render
  Module Products.PageTemplates.engine, line 368, in __call__
  Module z3c.pt.pagetemplate, line 198, in render
  Module chameleon.zpt.template, line 328, in render
  Module chameleon.template, line 229, in render
  Module chameleon.utils, line 20, in raise_with_traceback
  Module chameleon.template, line 200, in render
  Module 1ac8f88237956af17a352f1fc406ccdd, line 1880, in render
  Module 985090d925cc459bf0e69fde89f3e030, line 903, in render_master
  Module 615bdf9739ecd0ffd4d4eee8b7a6ebd5, line 498, in render_master
  Module zope.contentprovider.tales, line 76, in __call__
  Module zope.viewlet.manager, line 157, in update
  Module zope.viewlet.manager, line 163, in _updateViewlets
  Module Products.CMFPlone.resources.browser.resource, line 260, in update
  Module webresource._api, line 719, in render
  Module webresource._api, line 678, in resolve
webresource._api.ResourceMissingDependencyError: webresource._api.ResourceMissingDependencyError: Resource defines missing dependency: <PloneScriptResource name="plone-fullscreen", depends="['theme']">
```

what am I missing here?

2024-11-11 09:26 UTC, jensens commented
> > IMO custom should stay the last one.
> 
> +1 I think that would be the expected behavior. If I change something TTW it should override everything else (without using `!important` all the time)

I too agree

2024-12-03 16:43 UTC, thet commented
@jenkins-plone-org please run jobs

2024-12-03 21:19 UTC, thet commented
@jenkins-plone-org please run jobs

2024-12-04 00:02 UTC, stevepiercy commented
Should I use the news item as the documentation for this new feature?

https://github.com/plone/Products.CMFPlone/pull/4054/files#diff-b79fc648ba65de1bd4da45d2bd3181b51ec6ff5b95fcb0cc91125609d52ad0fc

2024-12-04 03:36 UTC, stevepiercy requested changes
While working on the documentation, I found a bug in the control panel that should be corrected either in this PR or a related one in the correct repository, if not this one.

- Visit https://classic.demo.plone.org/@@theming-controlpanel#autotoc-item-autotoc-2 (Site Setup > Theming > Advanced settings > Custom Styles)
- Click the link [Theming documentation](https://docs.plone.org/adapt-and-extend/theming), which goes to a 404.

The correct link and label are [Theming of Classic UI](https://6.docs.plone.org/classic-ui/theming/index.html).

![Screenshot 2024-12-03 at 7 35 42 PM](https://github.com/user-attachments/assets/3439b245-c278-4b3a-8e85-134414ecc04c)

2024-12-04 03:48 UTC, stevepiercy commented
PR created to address the bug in the control panel UI at https://github.com/plone/plone.app.theming/pull/248.

While I'm in there, should I update any other control panel message?

2024-12-04 07:39 UTC, ale-rt commented on Products/CMFPlone/tests/testResourceRegistries.py
> +    return bundle
What is the reason to move this code outside of the class?

2024-12-04 07:48 UTC, ale-rt commented on Products/CMFPlone/resources/browser/resource.py
> +            resource.depends = list(dependencies)
I think that use `map` and `filter` with two custom lambdas and then casting to a list can be replaced with a much more clear for cycle and probably performant for cycle.

2024-12-04 14:53 UTC, petschki requested changes
@thet I think we should rethink this and use the grouping api of `webresource`. If we move the resources with `depends="all"` to a new "deferred" ResourceGroup which gets resolved after the "theming" bundles then `webresource` does our work. See my experimental commit here: https://github.com/plone/Products.CMFPlone/commit/92a82ec016b40e63ec215f8cf12e3f18988e7209 ...

2024-12-05 07:58 UTC, ale-rt commented on Products/CMFPlone/tests/testResourceRegistries.py
> +    return bundle
But in the other class it is defined as a method... https://github.com/plone/Products.CMFPlone/pull/4054/files#diff-8ef40cff64bf27605c753443d198309a61a480a09ec62d66fed8152c607cb600R264

IMO leave it like it was or make the test classes inherit from a common class.

2024-12-05 08:01 UTC, ale-rt commented on Products/CMFPlone/resources/browser/resource.py
> +            # Remove None values, e.g. if no known JS resource was found
> Remove None values, e.g. if no known JS resource was found

This is for CSS right?
The code in this cycle and in the one above looks the same.
If the treatment for the resources is equal maybe it is better to move it to a method?

2024-12-06 05:40 UTC, closed without merging

2024-12-06 05:41 UTC, petschki commented
Closed this in favor of #4076