Allow bundles to be rendered after all other.
plone/Products.CMFPlone pull request #4074
Opened 2024-12-03 16:29 UTC by thet

*This is the Plone 6.0 backport of: https://github.com/plone/Products.CMFPlone/pull/4054*

JS and CSS resources can now be rendered after all other resources in their
resource group including the theme (e.g. the Barceloneta theme CSS).

There is a exception for custom CSS which can be defined in the theming
controlpanel. This one is always rendered as last style resource.

To render a resource after all other give it the "depends" value of "all". This
indicates that the resource depends on all other being rendered before. The
resource is then rendered as last resource of it's resource group.

This allows to override a theme with custom CSS from a bundle instead of having
to add the CSS customizations to the registry via the "custom_css" settings.
As a consequence, theme customization can now be done in the filesystem in
ordinary CSS files instead of being bound to a time consuming workflow which
involces upgrading the custom_css registry after every change.

2024-12-03 16:29 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-12-03 21:18 UTC, thet commented
@jenkins-plone-org please run jobs

2024-12-04 14:13 UTC, stevepiercy requested changes
Revisions to mention multiple bundles with "all", and some grammar and spelling.

2024-12-04 14:13 UTC, stevepiercy commented on Products/CMFPlone/resources/browser/resource.py
> +                    # A valid dependency or special dependency "all", which
```suggestion
                    # A valid dependency or a special dependency "all",
```

2024-12-04 14:13 UTC, stevepiercy commented on Products/CMFPlone/resources/browser/resource.py
> +                    # specifies that the bundle should be rendered last.
```suggestion
                    # meaning that all other bundles should render before these,
                    # making them the last to render.
                    # Multiple bundles with "all" will render in the order
                    # in which you declare them.
```

2024-12-04 14:13 UTC, stevepiercy commented on news/4074.feature
> +There is a exception for custom CSS which can be defined in the theming
```suggestion
There is an exception for custom CSS which can be defined in the theming
```

2024-12-04 14:13 UTC, stevepiercy commented on news/4074.feature
> +To render a resource after all other give it the "depends" value of "all". This
```suggestion
To render resources after all others, give them the "depends" value of "all".
```

2024-12-04 14:13 UTC, stevepiercy commented on news/4074.feature
> +indicates that the resource depends on all other being rendered before. The
```suggestion
For each of these resources, "all" indicates that the resource depends on all other resources, making it render after its dependencies.
```

2024-12-04 14:13 UTC, stevepiercy commented on news/4074.feature
> +resource is then rendered as last resource of it's resource group.
```suggestion
If you set multiple resources with "all", then they will render in the order in which you declare them.
```

2024-12-06 07:13 UTC, petschki commented
Close this in favor of #4077

2024-12-06 07:13 UTC, closed without merging